# Generated by Django 6.0.1 on 2026-02-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_about_amenities_contact_faq_gallery_terms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('image', models.ImageField(upload_to='testimonial/')),
            ],
        ),
        migrations.DeleteModel(
            name='testimonials',
        ),
    ]
