# Generated by Django 6.0.1 on 2026-02-15 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_testimonial_delete_testimonials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='menu_item',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
