# Generated by Django 6.0.1 on 2026-02-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0003_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(choices=[('The Grandeur', 'The Grandeur'), ('Elegant Stays', 'Elegant Stays'), ('The Wellness', 'The Wellness'), ('The Leisure', 'The Leisure'), ('The Experience', 'The Experience')], max_length=50)),
                ('image', models.ImageField(upload_to='gallery/')),
            ],
        ),
    ]
