# Generated by Django 6.0.1 on 2026-02-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0004_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='category_name',
            field=models.CharField(max_length=50),
        ),
    ]
