# Generated by Django 6.0.1 on 2026-02-10 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0006_contactenquiry_contactus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactenquiry',
            name='created_at',
        ),
    ]
