# Generated by Django 6.0.1 on 2026-02-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0007_remove_contactenquiry_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactenquiry',
            name='id',
        ),
        migrations.AddField(
            model_name='contactenquiry',
            name='enquiry_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
