# Generated by Django 6.0.1 on 2026-02-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0008_remove_contactenquiry_id_contactenquiry_enquiry_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='contactus_id',
        ),
        migrations.AddField(
            model_name='contactus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
