# Generated by Django 6.0.1 on 2026-02-10 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0009_remove_contactus_contactus_id_contactus_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='description',
        ),
    ]
