# Generated by Django 6.0.1 on 2026-02-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0011_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_rooms', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='rooms/')),
            ],
        ),
    ]
