# Generated by Django 6.0.1 on 2026-02-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0012_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Casa Suite', 'Casa Suite'), ('Deluxe', 'Deluxe'), ('Executive', 'Executive')], max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='total_rooms',
            field=models.IntegerField(),
        ),
    ]
