# Generated by Django 6.0.1 on 2026-02-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0017_alter_booking_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_rooms_booked',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
