# Generated by Django 6.0.1 on 2026-02-19 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0018_booking_total_rooms_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='total_rooms_booked',
        ),
    ]
