# Generated by Django 6.0.1 on 2026-02-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0019_remove_booking_total_rooms_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rooms_booked',
            field=models.IntegerField(default=1),
        ),
    ]
