# Generated by Django 6.0.1 on 2026-02-20 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0020_booking_rooms_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='rooms_booked',
        ),
    ]
