# Generated by Django 6.0.1 on 2026-03-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0021_remove_booking_rooms_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rooms_booked',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
