# Generated by Django 6.0.1 on 2026-03-12 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0028_rename_name_menuitem_item_name_alter_menuitem_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='price',
        ),
    ]
